before_script:
  - env
stages:
  - deploy
  - config
Deploy:
  stage: deploy
  script:
    - rm -rf /var/www/html/*
    - cp -r ${CI_PROJECT_DIR}/www/* /var/www/html/
    - rm -f /opt/heatmiser/*.py
    - cp -r ${CI_PROJECT_DIR}/utility/* /opt/heatmiser/
Config services:
  stage: config
  script:
    - cp relay-poll* /etc/systemd/system
    - cp heatmiser-parse* /etc/systemd/system
